### PR TITLE
README.md: Add model compatibility list

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by davidebeatrici** [comment]
@odya I listed `POW-HVM2.0H-12V` because it's in the `Manuals` section, but was it tested?

**Comment by odya** [comment]
No, I added a manuals section because during my research, I accumulated various manuals. I assumed that the 1.5, 2.0, 2.4, and 3.2 models are similar because they have mostly similar manuals. However, the code and registers were only tested on my 2.4kW/24v version. I apologize for any confusion.

I suggest moving the approved compatibility information to a separate section.

**Comment by davidebeatrici** [comment]
No worries, I understand.

Is the README good now?

**Comment by odya** [comment]
Yep. Thank you!

**Comment by davidebeatrici** [comment]
You're welcome!

**Comment by davidebeatrici** [comment]
Could you also update the repository's description, please?

**Pull request merged**
